[package]
name = "Project"
version = "1.0.0"
authors = []

[addresses]
account_address="0x8da8714ba335ab70f186aef2f81ca95c2531871dfdd432939896a057f57c9222"
creater="0x12"


[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", rev = "mainnet", subdir = "aptos-move/framework/aptos-framework" }
AptosTokenObjects = { git = "https://github.com/aptos-labs/aptos-core.git", rev = "mainnet", subdir = "aptos-move/framework/aptos-token-objects" }

