import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import WalletProvider from "@/components/WalletProvider";
import { Toaster } from "react-hot-toast";
const secondaryFont = localFont({
  src: "./fonts/Secondary.otf",
  variable: "--font-secondary",
  preload: true,
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${secondaryFont.variable} antialiased`}>
        <Toaster position="top-right" reverseOrder={false} />
        <WalletProvider>{children}</WalletProvider>
      </body>
    </html>
  );
}
